# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerCraft < Formula
  desc "A Docker Compose templating plugin"
  homepage "https://github.com/bloodmagesoftware/docker-craft"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/bloodmagesoftware/docker-craft/releases/download/v0.1.0/docker-craft_0.1.0_darwin_amd64.tar.gz"
      sha256 "9b078b758d9d23273fe1bbbc0b4752f533c4a33359b65eab56321a1081628358"

      def install
        bin.install "docker-craft"
      end
    end
    on_arm do
      url "https://github.com/bloodmagesoftware/docker-craft/releases/download/v0.1.0/docker-craft_0.1.0_darwin_arm64.tar.gz"
      sha256 "d57a09b0d97198eb95e43551100d16aef24c7a86497cd3b1a76c142ef75e5f7e"

      def install
        bin.install "docker-craft"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bloodmagesoftware/docker-craft/releases/download/v0.1.0/docker-craft_0.1.0_linux_amd64.tar.gz"
        sha256 "8fceb16ca92f759bad328ca04b433ce55aeda6e2321465fd6837ff46d71b02b9"

        def install
          bin.install "docker-craft"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bloodmagesoftware/docker-craft/releases/download/v0.1.0/docker-craft_0.1.0_linux_arm64.tar.gz"
        sha256 "7a004413bf099fabb051846f3cd6aa20b50240c08fdedef16e6a3e26de4e504c"

        def install
          bin.install "docker-craft"
        end
      end
    end
  end
end
