# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerCraft < Formula
  desc "A Docker Compose templating plugin"
  homepage "https://github.com/bloodmagesoftware/docker-craft"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/bloodmagesoftware/docker-craft/releases/download/v1.0.1/docker-craft_1.0.1_darwin_amd64.tar.gz"
      sha256 "cc9330a150603f6ea4692625fdbfa76fedce3a8bb4ff89460759f389ca6287da"

      def install
        bin.install "docker-craft"
      end
    end
    on_arm do
      url "https://github.com/bloodmagesoftware/docker-craft/releases/download/v1.0.1/docker-craft_1.0.1_darwin_arm64.tar.gz"
      sha256 "399c2d81d8f8e9500a4aeda5ef3cf20edeb0dbed4f0ebfdef9ff80d686587c79"

      def install
        bin.install "docker-craft"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bloodmagesoftware/docker-craft/releases/download/v1.0.1/docker-craft_1.0.1_linux_amd64.tar.gz"
        sha256 "4107a768afb4961bb0d4a72a39d34bfc4e42f8d9b5f91fdcf89f08c20e2d897e"

        def install
          bin.install "docker-craft"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bloodmagesoftware/docker-craft/releases/download/v1.0.1/docker-craft_1.0.1_linux_arm64.tar.gz"
        sha256 "8ae50c753f57d849001f12125c53a7a6f00557adc37c0c4e266779ff774d65d0"

        def install
          bin.install "docker-craft"
        end
      end
    end
  end
end
