# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scribe < Formula
  desc "SFTP based VCS"
  homepage "https://github.com/bloodmagesoftware/scribe"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bloodmagesoftware/scribe/releases/download/v0.0.1/scribe_Darwin_x86_64.tar.gz"
      sha256 "84cdc528e24d5bb145ba34e1f2893c18c131714b48ed0d04e3a17bf3e043f7d8"

      def install
        bin.install "scribe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bloodmagesoftware/scribe/releases/download/v0.0.1/scribe_Darwin_arm64.tar.gz"
      sha256 "1e71d5e7cf9ff869443d5ebd4a12663d1b043bd65e6e9d43371ac224da123b29"

      def install
        bin.install "scribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bloodmagesoftware/scribe/releases/download/v0.0.1/scribe_Linux_x86_64.tar.gz"
        sha256 "22983c4fdb8a7d4ee742803850ebef6c815eb70f31960a40c0b1253face5bc05"

        def install
          bin.install "scribe"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bloodmagesoftware/scribe/releases/download/v0.0.1/scribe_Linux_arm64.tar.gz"
        sha256 "c009fb85f7ecb35d03a43a45a39a3ba1aabdccf500e0f8803641a316a3de2464"

        def install
          bin.install "scribe"
        end
      end
    end
  end
end
